title: Nature
description: Carnet naturaliste â€¢ photos â€¢ terrain
remote_theme: just-the-docs/just-the-docs

# Look & navigation
color_scheme: light
search_enabled: true

# Ne pas afficher "Just the Docs" / Ã©lÃ©ments GitHub inutiles
footer_content: ""
gh_edit_link: false
last_edit_timestamp: false

# Organisation du menu (ordre + titres)
nav_sort: case_sensitive
aux_links:
  "ğŸ“¸ Photos":
    - "photos.html"
  "ğŸ—’ï¸ Carnet":
    - "carnet.html"
  "ğŸ“¬ Contact":
    - "contact.html"
