title: Nature
description: Carnet naturaliste â€¢ photos â€¢ terrain
remote_theme: just-the-docs/just-the-docs

# Project site GitHub Pages (important)
url: "https://ygeshors.github.io"
baseurl: "/nature"

color_scheme: light
search_enabled: true
permalink: pretty

footer_content: ""
gh_edit_link: false
last_edit_timestamp: false

aux_links:
  "ğŸ“¸ Photos":
    - "{{ '/photos/' | relative_url }}"
  "ğŸ—’ï¸ Carnet":
    - "{{ '/carnet/' | relative_url }}"
  "ğŸ“¬ Contact":
    - "{{ '/contact/' | relative_url }}"

just_the_docs:
  custom_css:
    - assets/css/custom.css
