title: Nature
description: Carnet naturaliste â€¢ photos â€¢ terrain
remote_theme: just-the-docs/just-the-docs

# Style & fonctionnalitÃ©s
color_scheme: light
search_enabled: true
permalink: pretty

# Nettoyage (moins "documentation")
footer_content: ""
gh_edit_link: false
last_edit_timestamp: false

# Liens en haut du menu (Ã  droite dans lâ€™en-tÃªte)
aux_links:
  "ğŸ“¸ Photos":
    - "/photos/"
  "ğŸ—’ï¸ Carnet":
    - "/carnet/"
  "ğŸ“¬ Contact":
    - "/contact/"

# Police Barlow personnalisÃ©e
just_the_docs:
  custom_css:
    - assets/css/custom.css
