title: Nature
description: Site nature et biodiversit√©

remote_theme: just-the-docs/just-the-docs

github:
  is_project_page: false

header_pages:
  - projets.md
  - photos.md
  - contact.md

permalink: pretty
show_downloads: false
