title: Nature
description: Carnet naturaliste â€¢ photos â€¢ terrain
remote_theme: just-the-docs/just-the-docs

# IMPORTANT pour un repo de type /nature/
url: "https://ygeshors.github.io"
baseurl: "/nature"

# Style & fonctionnalitÃ©s
color_scheme: light
search_enabled: true
permalink: pretty

# Nettoyage (moins "documentation")
footer_content: ""
gh_edit_link: false
last_edit_timestamp: false

# Liens en haut du menu
# (sans domaine, et avec le bon /nature/ devant)
aux_links:
  "ğŸ“¸ Photos":
    - "/nature/photos/"
  "ğŸ—’ï¸ Carnet":
    - "/nature/carnet/"
  "ğŸ“¬ Contact":
    - "/nature/contact/"

# Police Barlow personnalisÃ©e
just_the_docs:
  custom_css:
    - assets/css/custom.css
